version: '2'

services:

  api-server:
    build:
      context: ./api-server
    restart: always
    container_name: rpi-radio-api
    expose:
      - "50051" # gRPC
      - "8080"
    depends_on:
      - db
      - redis

  web-radio:
    build:
      context: ./web-radio
    restart: always
    container_name: rpi-radio
    expose:
      - "50051" # gRPC
    devices:
      - /dev/snd:/dev/snd

  app-server:
    build:
      context: ./app-server
    restart: always
    container_name: rpi-radio-app
    expose:
      - "8080"

  nginx:
    build:
      context: ./nginx
    restart: always
    container_name: rpi-radio-nginx
    ports:
      - "80:80"
    depends_on:
      - app-server
      - api-server

  redis:
    build:
      context: ./redis
    restart: always
    container_name: rpi-radio-redis
    expose:
      - 6379


  db:
    image: tobi312/rpi-postgresql
